[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/admin/login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/content"
  to = "/.netlify/functions/content"
  status = 200

[[redirects]]
  from = "/api/admin/change-password"
  to = "/.netlify/functions/admin-change-password"
  status = 200

[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events"
  status = 200

[[redirects]]
  from = "/api/cards"
  to = "/.netlify/functions/cards"
  status = 200
